name: CI/CD
on:
  push:
    branches: [ $default-branch ]
    tags: ['*']
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build-test-deploy-release:
    name: CI/CD
    uses: austenstone/.github/.github/workflows/angular.yml@main
    secrets: inherit
